---
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  GIT_USER: https://gitlab-ci-token:$CI_JOB_TOKEN

stages:
  - pre
  - build
  - deploy
  - post

include:
  # Stage: pre
  - "/deployment/webapp/check_release.yml"
  # Stage: build
  - "/deployment/webapp/build.yml"
  - "/deployment/webapp/env.yml"

  # Stage: deploy
  - "/deployment/webapp/deploy.yml"

  # Stage: post
  - "/deployment/webapp/uptimerobot.yml"
