---
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  GIT_USER: https://gitlab-ci-token:$CI_JOB_TOKEN
  TAG_BRANCH: 'git branch --contains tags/$CI_COMMIT_TAG'

stages:
  - build
  - deploy
  - post

include:
  # Stage: build
  - "/deployment/webapp/build.yml"
  - "/deployment/webapp/env.yml"

  # Stage: deploy
  - "/deployment/webapp/deploy.yml"

  # Stage: post
  - "/deployment/webapp/uptimerobot.yml"
