---
version: "2.4"

services:
  # Webapp
  webapp:
    image: ${CI_PROJECT_NAME}/webapp:$CI_COMMIT_SHORT_SHA
    container_name: ${CI_PROJECT_NAME}-webapp
    restart: always
    mem_limit: ${MEM_LIMIT_WEBAPP}
    logging:
      driver: "json-file"
      options:
        max-file: "${LOGS_MAX_FILE}"
        max-size: "${LOGS_MAX_SIZE}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CI_PROJECT_NAME}-webapp.tls=true"
      - "traefik.http.routers.${CI_PROJECT_NAME}-webapp.entrypoints=websecure"
      - "traefik.http.routers.${CI_PROJECT_NAME}-webapp.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${CI_PROJECT_NAME}-webapp.middlewares=gzip,redirect-to-https"
      - "traefik.http.routers.${CI_PROJECT_NAME}-webapp.rule=Host(`${DOMAIN}`)"
      - "traefik.docker.network=web"
      - "traefik.http.services.${CI_PROJECT_NAME}-webapp.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
