---
version: "2.4"

services:
  # Webapp
  webapp:
    image: ${CI_PROJECT_NAME}/webapp:$CI_COMMIT_SHORT_SHA
    container_name: ${CI_PROJECT_NAME}-webapp
    restart: always
    mem_limit: ${MEM_LIMIT_WEBAPP}
    logging:
      driver: "json-file"
      options:
        max-file: "${LOGS_MAX_FILE}"
        max-size: "${LOGS_MAX_SIZE}"
    labels:
      - traefik.enable=true
      - traefik.webapp=${CI_PROJECT_NAME}-webapp
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - web

networks:
  web:
    external: true
