---
  version: "2.2"
  
  services:
    # Webapp
    webapp:
      image: ${CI_PROJECT_NAME}/webapp:$CI_COMMIT_SHORT_SHA
      container_name: ${CI_PROJECT_NAME}-webapp
      restart: always
      mem_limit: ${MEM_LIMIT_WEBAPP}
      logging:
        driver: "json-file"
        options:
          max-file: "${LOGS_MAX_FILE}"
          max-size: "${LOGS_MAX_SIZE}"
      labels:
        - traefik.enable=true
        - traefik.webapp=${CI_PROJECT_NAME}-webapp
        - traefik.frontend.rule=Host:${DOMAIN}
        - traefik.docker.network=web
        - traefik.port=80
        - traefik.frontend.headers.customResponseHeaders=X-Robots-Tag :noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
        - "traefik.frontend.auth.basic.users=heply:$$apr1$$jlxVnLzz$$.DvFktmT6517Zqcs3ZZeF.,lima:$$apr1$$1tZeY41K$$722drij54GteY0v1kYFJ7."
      networks:
        - web

  networks:
    web:
      external: true
