---
build_webapp:
  stage: build
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  before_script:
    - apk update && apk upgrade && apk add --no-cache git
    - eval $TAG_BRANCH
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/webapp:latest || true
    - "docker build
      --build-arg=DOCKER_IMAGES_REPO=$DOCKER_IMAGES_REPO
      --cache-from $CI_REGISTRY_IMAGE/webapp:latest
      --tag $CI_REGISTRY_IMAGE/webapp:latest
      --file deployment/webapp/build/Dockerfile
      ./"
    - docker push $CI_REGISTRY_IMAGE/webapp:latest
    - docker tag $CI_REGISTRY_IMAGE/webapp:latest $CI_REGISTRY_IMAGE/webapp:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/webapp:$CI_COMMIT_SHORT_SHA
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "develop"'
